let items = [
    {
      id: 1,
      title: 'Cable Roller',
      seller: 'Issam Alzouby',
      condition: 'New',
      price: 9.99,
      details: 'PLA Cable Roller, Stay Organized, Stay Creative!',
      image: '/images/product1.png',
      active: true,
    },

   { id: 2,
    title: 'Squid Buddy',
    seller: 'Issam Alzouby',
    condition: 'New',
    price: 10.99,
    details: 'PLA Cable Roller, Stay Organized, Stay Creative!',
    image: '/images/product2.png',
    active: true,
  },
  { id: 3,
    title: 'Shelves',
    seller: 'Issam Alzouby',
    condition: 'New',
    price: 49.99,
    details: 'PLA Cable Roller, Stay Organized, Stay Creative!',
    image: '/images/product3.png',
    active: true,
  },
  { id: 4,
    title: 'Groot',
    seller: 'Issam Alzouby',
    condition: 'New',
    price: 19.99,
    details: 'PLA Cable Roller, Stay Organized, Stay Creative!',
    image: '/images/product4.png',
    active: true,
  },
  { id: 5,
    title: 'Plant Pots',
    seller: 'Issam Alzouby',
    condition: 'New',
    price: 9.99,
    details: 'PLA Cable Roller, Stay Organized, Stay Creative!',
    image: '/images/product5.png',
    active: true,
  },
  { id: 6,
    title: 'Pokemon Ball',
    seller: 'Issam Alzouby',
    condition: 'Used',
    price: 199.99,
    details: 'PLA Cable Roller, Stay Organized, Stay Creative!',
    image: '/images/product6.png',
    active: true,
  }

  ];
  
  module.exports = items;
  